### ISSUE TITLE
Latest Version of Benesh for Ballet Book 3 Worksheets 

### ISSUE THREAD

**Issue by rryman** [rryman/BB3-Worksheets#3]
[BB3WorksheetsSept12.2018.pdf](https://github.com/rryman/BB3-Worksheets/files/2558938/BB3WorksheetsSept12.2018.pdf)

**Comment by rsryman** [comment]
[BB3WorksheetsNov8,2018.pdf](https://github.com/rryman/BB3-Worksheets/files/2563393/BB3WorksheetsNov8.2018.pdf)

**Comment by rsryman** [comment]
[BB3WorksheetsNov9,2018.pdf](https://github.com/rryman/BB3-Worksheets/files/2573064/BB3WorksheetsNov9.2018.pdf)

**Comment by rsryman** [comment]
[BB3WorksheetsNov12,2018.pdf](https://github.com/rryman/BB3-Worksheets/files/2573781/BB3WorksheetsNov12.2018.pdf)

**Comment by rsryman** [comment]
[BB3WorksheetsNov14,2018.pdf](https://github.com/rryman/BB3-Worksheets/files/2582328/BB3WorksheetsNov14.2018.pdf)

**Comment by rsryman** [comment]
Replace previously uploaded pdf re Nov 14/18:
[BB3WorksheetsNov14,2018.pdf](https://github.com/rryman/BB3-Worksheets/files/2582464/BB3WorksheetsNov14.2018.pdf)

**Comment by rryman** [comment]
Robyn has edited pages 1 - 8 (inclusive) - on January 13th 2019 at 11:00 am.

- [ ] Rhonda to proofread

[BB3Worksheets13JanP8.pdf](https://github.com/rryman/BB3-Worksheets/files/2753235/BB3Worksheets13JanP8.pdf)

**Comment by rryman** [comment]
Robyn has edited pages 9 - 11 (inclusive) - on January 16th 2019 at 5:00 pm.

- [ ] Rhonda to proofread

[BB3Worksheets16JanP11.pdf](https://github.com/rryman/BB3-Worksheets/files/2766226/BB3Worksheets16JanP11.pdf)

**Comment by rryman** [comment]
Robyn has edited pages 12 - 16 (inclusive) - on January 17th 2019 at 11:20 am.

- [ ] Rhonda to proofread

[BB3Worksheets17JanP16.pdf](https://github.com/rryman/BB3-Worksheets/files/2769649/BB3Worksheets17JanP16.pdf)

**Comment by rryman** [comment]
Robyn has edited pages 17 - 20 (inclusive) - on January 22nd 2019 at 10:20 am.

- [ ]  Rhonda to proofread

- [ ] Rhonda to give input on the outstanding question re "Page 20 formatting issue #28"
(depending on the solution this may change the page numbers and I'll have to update them in Adobe Illustrator as I edit each page moving forward)

[BB3Worksheets20JanP22.pdf](https://github.com/rryman/BB3-Worksheets/files/2783430/BB3Worksheets20JanP22.pdf)

**Comment by rsryman** [comment]
p. 18: re Plié in 5th and 4th final frame: 
There is an extra horizontal line at the start of the movement line to the R hand

**Comment by rryman** [comment]
Robyn has edited pages 26- 31 (inclusive) - on January 26th 2019 at 11:00 am.

 - [ ] Rhonda 

[BB3Worksheets26JanP31.pdf](https://github.com/rryman/BB3-Worksheets/files/2799172/BB3Worksheets26JanP31.pdf)
to proofread

**Comment by rsryman** [comment]
Question re p. 26: Rhonda agrees that students need to recopy the in-stave notation for the first 2 sequences because the feet change on the beaten jump, but perhaps rather than copying the same thing again, we should provide in-stave notation minus _repeat_ signs and add instructions (if there is room?): 
Recopy the "same side" and "other side" examples in the empty staves below, then add "alternate sides" _repeat_ signs to the bottom stave.

**Comment by rryman** [comment]
Robyn has edited for the use of "copy" and "rewrite" - on January 27th 2019 at 1:15 pm.

- [ ]  Rhonda to proofread (see issue Copy and Rewrite #32)

[BB3Worksheets27JanP31.pdf](https://github.com/rryman/BB3-Worksheets/files/2800347/BB3Worksheets27JanP31.pdf)

**Comment by rryman** [comment]
Robyn has edited pages 32- 35 (inclusive) - on January 28th 2019 at 10:30 am.  

- [ ] Rhonda to proofread (see issue "Page 32 (Book 3 page 43) #33")

[BB3Worksheets28JanP35.pdf](https://github.com/rryman/BB3-Worksheets/files/2803728/BB3Worksheets28JanP35.pdf)

**Comment by rsryman** [comment]
Just a tiny update to p. 32 line 4: italicize _Book 3_

**Comment by rryman** [comment]
Robyn has edited pages 36- 40 (inclusive) - on January 29th 2019 at 4:00 pm.

- [ ] Rhonda to proofread

- [ ] Rhonda to check the headings on these pages to see if she agrees with the changes.
If not, Rhonda will start a different issue in GitHub to discuss what needs to be changed.

[BB3Worksheets29JanP40.pdf](https://github.com/rryman/BB3-Worksheets/files/2809627/BB3Worksheets29JanP40.pdf)

**Comment by rsryman** [comment]
Good solutions re p. 36-40. 

Just a thought for your consideration re Grand Battement pp. 39-40 (this would also apply to Adage pp. 41-42). If you agree I'll open a new Issue. The current way allows students to copy both versions of Grand Battement. OR we could put both examples on the same page and give them the option of copying either (but this would cut out a page and cause repagination).

**Comment by rryman** [comment]
Robyn has edited pages 39-42 (inclusive) - on January 30th 2019 at 1:00 pm.

Old pages 39/40 and 41/42 were combined in this version. The page numbers from the previous pdf will now be off by two pages. There is presently two blank pages in this pdf. Robyn is adjusting the pages one at a time as she works on editing them. Robyn has to remember to change the page numbers as she goes.

- [ ] Rhonda to proofread (check page numbers from here on out)

[BB3Worksheets30JanP42.pdf](https://github.com/rryman/BB3-Worksheets/files/2813783/BB3Worksheets30JanP42.pdf)

**Comment by rryman** [comment]
Robyn has edited pages 43- 45 (inclusive) - on January 31st 2019 at 2:00 pm.

- [ ] Rhonda to proofread. Please pay careful attention to the 5th position signs as I have changed them all to match the rest of the worksheets.

[BB3Worksheets31JanP45.pdf](https://github.com/rryman/BB3-Worksheets/files/2818679/BB3Worksheets31JanP45.pdf)

**Comment by rryman** [comment]
Robyn has edited pages 46-48 (inclusive) - on February 1st 2019 at 1:00 pm.

- [ ] Rhonda to proofread (see issue "Page 48 (Book 3 p. 64) - More on Reverse Repeats #39")

[BB3Worksheets1FebP48.pdf](https://github.com/rryman/BB3-Worksheets/files/2822715/BB3Worksheets1FebP48.pdf)

**Comment by rsryman** [comment]
Pp. 46-47 OK. Re p. 48:

For the text, refer to Issue #39 and Issue #40.
Please check the starting position 5th L ft fr: dot too big?

**Comment by rryman** [comment]
Robyn has edited pages 49-51 (inclusive) - on February 2nd 2019 at 4:30 pm.
- [ ] Rhonda to proofread

Outstanding Issues:
- [ ] Page 48 (Book 3 page 64) #41 
- [ ] Page 49 (Book 3 page 65) #42 

[BB3Worksheets2FebP51.pdf](https://github.com/rryman/BB3-Worksheets/files/2824877/BB3Worksheets2FebP51.pdf)

**Comment by rryman** [comment]
Robyn has edited pages 52-54 (inclusive) - on February 4th 2019 at 11:30 am.

- [ ] Rhonda to proofread

Outstanding Issues:

- [ ] BB3WorksheetsWordingReRed-LinedStavePaper #40 
- [ ] Page 49 (Book 3 page 65) #42
- [ ] Extra pages #44

[BB3Worksheets4FebP54.pdf](https://github.com/rryman/BB3-Worksheets/files/2828953/BB3Worksheets4FebP54.pdf)

**Comment by rryman** [comment]
Robyn has edited pages 55-57 (inclusive) - on February 5th 2019 at 3:00 am.

- [ ] Rhonda to proofread

Outstanding Issue:

- [ ] Updated Page 50 text #45

[BB3Worksheets5FebP57.pdf](https://github.com/rryman/BB3-Worksheets/files/2833602/BB3Worksheets5FebP57.pdf)

**Comment by rsryman** [comment]
Pee p. 50, see #45 :
_Book 3_ on page 67 -> _Book 3_ p. 67

**Comment by rryman** [comment]
Robyn has edited pages 58-62 (inclusive) - on February 6th 2019 at 11:45 am.

- [ ] Rhonda to proofread

[BB3Worksheets6FebP62.pdf](https://github.com/rryman/BB3-Worksheets/files/2837329/BB3Worksheets6FebP62.pdf)
